/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedScholarshipsRouteImport } from './routes/_authenticated/scholarships'
import { Route as AuthenticatedSchemesRouteImport } from './routes/_authenticated/schemes'
import { Route as AuthenticatedLoansRouteImport } from './routes/_authenticated/loans'
import { Route as AuthenticatedInternshipsRouteImport } from './routes/_authenticated/internships'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedCompetitionsRouteImport } from './routes/_authenticated/competitions'
import { Route as AuthenticatedCareersRouteImport } from './routes/_authenticated/careers'
import { Route as AuthenticatedBlogRouteImport } from './routes/_authenticated/blog'
import { Route as AuthenticatedCareersSlugRouteImport } from './routes/_authenticated/careers/$slug'
import { Route as AuthenticatedBlogSlugRouteImport } from './routes/_authenticated/blog/$slug'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScholarshipsRoute =
  AuthenticatedScholarshipsRouteImport.update({
    id: '/scholarships',
    path: '/scholarships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchemesRoute = AuthenticatedSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLoansRoute = AuthenticatedLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInternshipsRoute =
  AuthenticatedInternshipsRouteImport.update({
    id: '/internships',
    path: '/internships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompetitionsRoute =
  AuthenticatedCompetitionsRouteImport.update({
    id: '/competitions',
    path: '/competitions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCareersRoute = AuthenticatedCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlogRoute = AuthenticatedBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCareersSlugRoute =
  AuthenticatedCareersSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedCareersRoute,
  } as any)
const AuthenticatedBlogSlugRoute = AuthenticatedBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/blog': typeof AuthenticatedBlogRouteWithChildren
  '/careers': typeof AuthenticatedCareersRouteWithChildren
  '/competitions': typeof AuthenticatedCompetitionsRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/internships': typeof AuthenticatedInternshipsRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/schemes': typeof AuthenticatedSchemesRoute
  '/scholarships': typeof AuthenticatedScholarshipsRoute
  '/blog/$slug': typeof AuthenticatedBlogSlugRoute
  '/careers/$slug': typeof AuthenticatedCareersSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/blog': typeof AuthenticatedBlogRouteWithChildren
  '/careers': typeof AuthenticatedCareersRouteWithChildren
  '/competitions': typeof AuthenticatedCompetitionsRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/internships': typeof AuthenticatedInternshipsRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/schemes': typeof AuthenticatedSchemesRoute
  '/scholarships': typeof AuthenticatedScholarshipsRoute
  '/blog/$slug': typeof AuthenticatedBlogSlugRoute
  '/careers/$slug': typeof AuthenticatedCareersSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/blog': typeof AuthenticatedBlogRouteWithChildren
  '/_authenticated/careers': typeof AuthenticatedCareersRouteWithChildren
  '/_authenticated/competitions': typeof AuthenticatedCompetitionsRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRoute
  '/_authenticated/internships': typeof AuthenticatedInternshipsRoute
  '/_authenticated/loans': typeof AuthenticatedLoansRoute
  '/_authenticated/schemes': typeof AuthenticatedSchemesRoute
  '/_authenticated/scholarships': typeof AuthenticatedScholarshipsRoute
  '/_authenticated/blog/$slug': typeof AuthenticatedBlogSlugRoute
  '/_authenticated/careers/$slug': typeof AuthenticatedCareersSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/blog'
    | '/careers'
    | '/competitions'
    | '/courses'
    | '/internships'
    | '/loans'
    | '/schemes'
    | '/scholarships'
    | '/blog/$slug'
    | '/careers/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/blog'
    | '/careers'
    | '/competitions'
    | '/courses'
    | '/internships'
    | '/loans'
    | '/schemes'
    | '/scholarships'
    | '/blog/$slug'
    | '/careers/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/blog'
    | '/_authenticated/careers'
    | '/_authenticated/competitions'
    | '/_authenticated/courses'
    | '/_authenticated/internships'
    | '/_authenticated/loans'
    | '/_authenticated/schemes'
    | '/_authenticated/scholarships'
    | '/_authenticated/blog/$slug'
    | '/_authenticated/careers/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/scholarships': {
      id: '/_authenticated/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof AuthenticatedScholarshipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schemes': {
      id: '/_authenticated/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof AuthenticatedSchemesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loans': {
      id: '/_authenticated/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthenticatedLoansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/internships': {
      id: '/_authenticated/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof AuthenticatedInternshipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competitions': {
      id: '/_authenticated/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof AuthenticatedCompetitionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/careers': {
      id: '/_authenticated/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof AuthenticatedCareersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blog': {
      id: '/_authenticated/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AuthenticatedBlogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/careers/$slug': {
      id: '/_authenticated/careers/$slug'
      path: '/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof AuthenticatedCareersSlugRouteImport
      parentRoute: typeof AuthenticatedCareersRoute
    }
    '/_authenticated/blog/$slug': {
      id: '/_authenticated/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof AuthenticatedBlogSlugRouteImport
      parentRoute: typeof AuthenticatedBlogRoute
    }
  }
}

interface AuthenticatedBlogRouteChildren {
  AuthenticatedBlogSlugRoute: typeof AuthenticatedBlogSlugRoute
}

const AuthenticatedBlogRouteChildren: AuthenticatedBlogRouteChildren = {
  AuthenticatedBlogSlugRoute: AuthenticatedBlogSlugRoute,
}

const AuthenticatedBlogRouteWithChildren =
  AuthenticatedBlogRoute._addFileChildren(AuthenticatedBlogRouteChildren)

interface AuthenticatedCareersRouteChildren {
  AuthenticatedCareersSlugRoute: typeof AuthenticatedCareersSlugRoute
}

const AuthenticatedCareersRouteChildren: AuthenticatedCareersRouteChildren = {
  AuthenticatedCareersSlugRoute: AuthenticatedCareersSlugRoute,
}

const AuthenticatedCareersRouteWithChildren =
  AuthenticatedCareersRoute._addFileChildren(AuthenticatedCareersRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBlogRoute: typeof AuthenticatedBlogRouteWithChildren
  AuthenticatedCareersRoute: typeof AuthenticatedCareersRouteWithChildren
  AuthenticatedCompetitionsRoute: typeof AuthenticatedCompetitionsRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedInternshipsRoute: typeof AuthenticatedInternshipsRoute
  AuthenticatedLoansRoute: typeof AuthenticatedLoansRoute
  AuthenticatedSchemesRoute: typeof AuthenticatedSchemesRoute
  AuthenticatedScholarshipsRoute: typeof AuthenticatedScholarshipsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBlogRoute: AuthenticatedBlogRouteWithChildren,
  AuthenticatedCareersRoute: AuthenticatedCareersRouteWithChildren,
  AuthenticatedCompetitionsRoute: AuthenticatedCompetitionsRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedInternshipsRoute: AuthenticatedInternshipsRoute,
  AuthenticatedLoansRoute: AuthenticatedLoansRoute,
  AuthenticatedSchemesRoute: AuthenticatedSchemesRoute,
  AuthenticatedScholarshipsRoute: AuthenticatedScholarshipsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
